[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

  [functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"